### ISSUE TITLE
Textarea overlapping pre tag 

### ISSUE THREAD

**Issue by zverbeta** [PrismJS/live#1]
Hi, i found a bug in the demo for "specific max height" box, if we resize textarea control it overlap pre tag 

![prisma_live_overlap](https://user-images.githubusercontent.com/6248327/45682877-59996800-bb4a-11e8-994a-a5a09c8ddc62.png)

**Comment by LeaVerou** [comment]
Ah, I should apply `resize: both`.

**Comment by LeaVerou** [comment]
Also, how did you discover this? I haven't announced it anywhere, since it's still WIP :)
Good to see someone helping with bug reports!

**Comment by zverbeta** [comment]
I made pull request, maybe its helps

**Comment by zverbeta** [comment]
You do cool things, I just became a subscriber :)
