### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by dordchn** [PrismJS/live#18]
Currently there is no license for the library.
I assume it was intended to be released under the MIT license, just like Prism?

Without a license, it is illegal for users to use in their products (unless they have explicit permission from the owner).

**Comment by LeaVerou** [comment]
I just added one, though do note that this is a pretty early stage/untested library so I'd be a bit hesitant to recommend using it in production regardless of license status! Unless you're willing to test extensively and report back of course, for which we'd be very grateful :)
