### ISSUE TITLE
Disable textarea's spellcheck by default

### ISSUE THREAD

**Issue by dordchn** [PrismJS/live#28]
By default, spellcheck is enabled for textareas (tested on Chrome & Firefox).
As it is meant to show code, I believe it makes sense to disable it by default.

![image](https://user-images.githubusercontent.com/4134084/161059149-8bc05683-5d3d-4b4c-a834-bfaf4693492c.png)

(Users can easily switch it off when using textarea, but when they use pre tags it is less convenient for them right now.)

**Comment by dordchn** [comment]
Ah, I see there's a [pull request](https://github.com/PrismJS/live/pull/13) for that.
It's quite old though, any update?

**Comment by LeaVerou** [comment]
Just merged it!
