### ISSUE TITLE
Line numbers plugin + prism live = cursor displays in wrong location.

### ISSUE THREAD

**Issue by AgentEnder** [PrismJS/live#5]
## Issue:
Appears to be caused by a misalignment of textarea and pre tag due to the margin added by line numbers.

## Evidence:
Proof of misalignment:
![image](https://user-images.githubusercontent.com/6933928/94083544-13c2aa80-fdc9-11ea-89c1-6ca42c8e613d.png)

Cursor displacement:
[![Image from Gyazo](https://i.gyazo.com/4b77e2d6377205f020b23d361719704f.gif)](https://gyazo.com/4b77e2d6377205f020b23d361719704f)

## Live demo: 
https://codepen.io/agentender/full/abNVxvV
Note, to reproduce the issue change the prism-live cdn link to target the master branch.

**Comment by AgentEnder** [comment]
My main concern with this is whether the fix belongs here, or in the line-numbers plugin

**Comment by LeaVerou** [comment]
> My main concern with this is whether the fix belongs here, or in the line-numbers plugin

Unfortunately, this will be unclear until a fix is known. If the fix depends on the line numbers plugin, then it belongs there. If the fix just needs the alignment code to be more robust, then it belongs here.

**Comment by AgentEnder** [comment]
@LeaVerou I opened a PR here with the fix, ill let you determine if it belongs here or there and create a new PR if necessary

**Comment by AgentEnder** [comment]
Fixed by PR #6
